services:
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lucid
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':1337'
      MERCURE_PUBLISHER_JWT_KEY: 'Change'
      MERCURE_SUBSCRIBER_JWT_KEY: 'Change'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3333
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - '1337:1337'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
volumes:
  psql-data:
  redis-data:
  mercure_data:
  mercure_config:
